# Generated by Django 6.0.6 on 2026-07-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_tasadolar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasadolar',
            name='tasa',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
